### ISSUE TITLE
Publishing as a gem

### ISSUE THREAD

**Issue by JonnieCache** [pcreux/rspec-set#1]
Are you planning to publish this gem to rubygems.org?

Or you could submit it as a patch to rspec itself.

Seems a shame to leave it all on its own here on github now that youve written the gemspec and everything!

**Comment by pcreux** [comment]
I gonna try to put some time aside today.... or next week to publish it as a gem. :)

**Comment by pcreux** [comment]
I assume you can add to your bundle:

gem rspec-set, :git => 'git://github.com/pcreux/rspec-set.git'

**Comment by JonnieCache** [comment]
I'm using

`gem 'rspec-set', :git => 'https://github.com/pcreux/rspec-set.git'`

I can't remember if bundler accepts the git:// protocol or not.

**Comment by pcreux** [comment]
Oh, ok. And it works?

Looks like I did everything to publish rspec-set as a gem and then forgot about it.

**Comment by pcreux** [comment]
http://rubygems.org/gems/rspec-set :)
