### ISSUE TITLE
set() somehow stopping let() from redefining methods

### ISSUE THREAD

**Issue by eliaslevy** [pcreux/rspec-set#2]
I found what I think is an obscure bug in set() while testing some of my models.  The following spec should execute successfully but it fails:

require "spec_helper"
describe "redefined let" do
  set(:business    ) { Business.first }
  set(:person      ) { Person.create :name_first => "first" , :name_last => "last" , :email => 'a@wx.yz', :business => business }

  context 'context1' do
    let(:x)     { "foo" }
    it  { x.should eq 'foo' }
  end
  context 'context2' do
    let(:x)     { "bar" }
    it { x.should eq 'bar' }
  end
end

As you can set let() is redefining x within each child context, but the second test fails, x still returns "foo".

If I comment out the second set (the :person one), the all tests work.  This occurs regardless of the symbol name I use, and it also occurs if I replace some other models instead of Person, e.g. replacing the second line with:

  set(:computer    ) { Computer.create :name => 'namer', :hostname => 'hostname', :business => business }

also fails.  It fails whether I use create or new  Note that I can actually use the instance created by set, it is valid, and it is stored in the DB, so its not a failure of the block that is leading to the problem.

It does not fail if I the second set does create an instance of Rails model.

Thoughts?

**Comment by eliaslevy** [comment]
I think it may be related to the fact that the second models I tried, both depended on the first (business).  If instead I create a second business object, then the failure goes away.  So there seems to be something screwy if you use a variable defined with set() within another set() definition.

**Comment by pcreux** [comment]
Mmmh... Interesting! I don't see how set() could be involved in that though.

I'll try to reproduce this issue.

Thanks for sharing this!
