### ISSUE TITLE
Support rspec 3

### ISSUE THREAD

**Issue by bmulholland** [pcreux/rspec-set#7]
What needs to be done here? How can I help out?

**Comment by freemanoid** [comment]
I use it with rspec 3 for several months and haven't got into troubles so far.

**Comment by bmulholland** [comment]
That's odd. I tried upgrading some time ago and got errors. I verified that with @pcreux at the time. I just tried upgrading again and I'm still getting errors wherever I use `set`:

```
     Failure/Error: set(:organization) { create(:organization_with_events, event_contract: contract) }
     RuntimeError:
       let declaration `contract` accessed in a `before(:context)` hook at:
         /Users/bmulholland/dev/contractually/spec/mailers/contract_activity_mailer_spec.rb:10:in `block (2 levels) in <top (required)>'

       `let` and `subject` declarations are not intended to be called
       in a `before(:context)` hook, as they exist to define state that
       is reset between each example, while `before(:context)` exists to
       define state that is shared across examples in an example group.
```

**Comment by bmulholland** [comment]
I have rather complex relationships, and this code is very common throughout my tests:

```
  set(:contract) { create(:contract) }
  let(:organization) { contract.owner }
  let(:user) { organization.owner }
  set(:org_access) { create(:organization_access, organization: organization) }
```

It is that second set that generates the error. This is a regression since rspec 2.x and a rough guess is it affects ~25% of my tests. Looks like I can fix it by instead using `contract.owner` instead of `organization` in the second set. Lots of changes to make...

**Comment by freemanoid** [comment]
Yes, the code inside `set` executes in `before(:context)` and it can reference himself only. Not sure if that was different in rspec 2.

**Comment by bmulholland** [comment]
Yeah, the above code worked fine in rspec 2.

**Comment by pcreux** [comment]
Works fine with RSpec 3 as long as you don't reference a model defined in a `let` block in a `set` block.

**Comment by bmulholland** [comment]
Any ideas on a way to improve the error it throws? Perhaps catch it in `set` and throw a more helpful error instead? That way I won't have to remember to mention it every time I onboard a dev :)
