### ISSUE TITLE
Support Sequel

### ISSUE THREAD

**Issue by elado** [pcreux/rspec-set#8]
I use Sequel, and rspec-set can't run without ActiveRecord.

**Comment by pcreux** [comment]
Hello @elado,

I haven't used sequel much. rspec-set requires the following API from ActiveRecord `new_record?`, `reload`, `destroyed?`. Do you use objects that implements some sort of Active Record or Data Mapper pattern? If they respond to such method, then it's not hard to get rspec-set to play nicely with them.

Have a look at the code, it's only 30 lines or so. It should be easy to make your own. :)

**Comment by pcreux** [comment]
Closing this issue as it hasn't been updated for 4 months.
